title: Humble Pied
subtitle: "One inspiring creative sharing one piece of advice, all over video chat."
author: Mig Reyes
description: "One inspiring creative sharing one piece of advice, all over video chat."

auto: true
source: .
exclude: [.DS_Store, .gitignore, .sass-cache, _drafts, _site, public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:categories/:title
markdown: rdiscount
pygments: true