# Site settings
title: Five Thrive
email: support@fivethrive.com
description: "Shopify Partner Phoenix | Software Development Phoenix | Ruby on Rails Phoenix | Modern software development company specializing in Ruby on Rails and Shopify development expertise"
baseurl: "http://fivethrive.com"
twitter_username: fivethrive
github_username:  fivethrive

exclude: [Gemfile, Gemfile.lock, Rakefile, README.md]

# Build settings
markdown: kramdown
permalink: pretty
